name: Build Lunatic Clang
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'
    
jobs:
  build-clang:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Prepare Build Script
        uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: bash ci.sh deps
      - name: Start Building
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_MAIL: ${{ secrets.GIT_MAIL }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
        run: bash build-clang.sh
